from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from django.core.files import File
from django.utils import timezone
from datetime import timedelta
from pathlib import Path

from apps.catalog.models import Brand, Category, Inventory, Product, ProductImage, TaxClass
from apps.orders.models import Coupon, StoreSetting

User = get_user_model()
IMAGE_DIR = Path(__file__).resolve().parents[2] / "fixtures" / "product-images"

CATEGORIES = [
    ("Audio", "audio", "Headphones, earbuds, and speakers designed for daily listening."),
    ("Charging", "charging", "Chargers, cables, and power accessories."),
    ("Storage", "storage", "Drives and cards for photos, work, and backups."),
    ("Wearables", "wearables", "Watches and bands that stay out of the way."),
    ("Computing", "computing", "Laptops and essentials for work and study."),
    ("Gaming", "gaming", "Controllers, headsets, and play accessories."),
    ("Home Appliances", "home-appliances", "Practical appliances for smaller Indian homes."),
    ("Kitchen", "kitchen", "Compact kitchen tools that earn their counter space."),
]

BRANDS = [
    ("Harbor", "harbor"),
    ("Lumen Forge", "lumen-forge"),
    ("Pebble & Co", "pebble-and-co"),
    ("Northline", "northline"),
    ("Kettlehouse", "kettlehouse"),
]

TAX = [
    ("GST 18% Electronics", "8518", "9.00", "9.00", "18.00"),
    ("GST 12% Appliances", "8509", "6.00", "6.00", "12.00"),
    ("GST 5% Essentials", "8418", "2.50", "2.50", "5.00"),
]

PRODUCTS = [
    {
        "name": "Harbor Pulse Earbuds",
        "sku": "HB-PLSE-01",
        "short": "Compact wireless earbuds with a calm, balanced sound signature.",
        "description": "Harbor Pulse is built for commutes and long workdays. The charging case is pocketable, the stems stay discreet, and the default EQ favours voices over bass theatre.",
        "mrp": "499.00",
        "price": "399.00",
        "tax": 0,
        "category": "audio",
        "brand": "harbor",
        "stock": 48,
        "featured": True,
        "bestseller": True,
        "specs": {"driver": "10mm", "battery": "28 hours with case", "connectivity": "Bluetooth 5.3"},
    },
    {
        "name": "Lumen Forge Studio Headphones",
        "sku": "LF-STUD-02",
        "short": "Over-ear headphones with a wide, unfatiguing soundstage.",
        "description": "A closed-back studio headphone for editing, calls, and evening listening. The headband uses a soft knit pad instead of sticky leatherette.",
        "mrp": "899.00",
        "price": "749.00",
        "tax": 0,
        "category": "audio",
        "brand": "lumen-forge",
        "stock": 22,
        "featured": True,
        "bestseller": False,
        "specs": {"type": "Closed-back", "impedance": "32 ohm", "cable": "Detachable 1.5m"},
    },
    {
        "name": "Pebble Shift Bluetooth Speaker",
        "sku": "PB-SHFT-03",
        "short": "A fabric-clad speaker that does not shout for attention.",
        "description": "Pebble Shift is sized for a desk or balcony table. IPX4 splash resistance and a 12-hour battery make it useful beyond the living room.",
        "mrp": "599.00",
        "price": "449.00",
        "tax": 0,
        "category": "audio",
        "brand": "pebble-and-co",
        "stock": 35,
        "featured": False,
        "bestseller": True,
        "specs": {"output": "20W", "battery": "12 hours", "rating": "IPX4"},
    },
    {
        "name": "Northline Loop Wired Earbuds",
        "sku": "NL-LOOP-19",
        "short": "Tangle-light wired earbuds for calls and commute audio.",
        "description": "Northline Loop is a 3.5mm pair for phones and laptops that still have a jack. The cable is flat so it does not knot in a pocket, and the mic is tuned for street-level calls rather than studio booths.",
        "mrp": "179.00",
        "price": "129.00",
        "tax": 0,
        "category": "audio",
        "brand": "northline",
        "stock": 90,
        "featured": False,
        "bestseller": True,
        "specs": {"connector": "3.5mm", "driver": "8mm", "cable": "1.2m flat"},
    },
    {
        "name": "Pebble Reed In-Ear Monitors",
        "sku": "PB-REED-20",
        "short": "Wired in-ears with a calm midrange for playlists and practice.",
        "description": "Pebble Reed uses a single dynamic driver and a memory-wire over-ear hook so they stay put on a walk. The stock tips include three sizes because one silicone shape never fits everyone.",
        "mrp": "249.00",
        "price": "199.00",
        "tax": 0,
        "category": "audio",
        "brand": "pebble-and-co",
        "stock": 64,
        "featured": False,
        "bestseller": False,
        "specs": {"driver": "10mm dynamic", "connector": "3.5mm", "impedance": "16 ohm"},
    },
    {
        "name": "Harbor Drift Neckband",
        "sku": "HB-DRFT-21",
        "short": "A light Bluetooth neckband that survives a sweaty commute.",
        "description": "Harbor Drift sits on the collar instead of in a case you will lose. Magnetic earbuds click together when not in use, and the 18-hour claim is for mixed playback, not a paused brochure number.",
        "mrp": "349.00",
        "price": "279.00",
        "tax": 0,
        "category": "audio",
        "brand": "harbor",
        "stock": 55,
        "featured": True,
        "bestseller": True,
        "specs": {"battery": "18 hours", "connectivity": "Bluetooth 5.3", "rating": "IPX5"},
    },
    {
        "name": "Lumen Forge USB-C DAC Dongle",
        "sku": "LF-DAC-22",
        "short": "A pocket DAC that gives phones and laptops a cleaner headphone jack.",
        "description": "Lumen Forge DAC is for wired listening on USB-C devices. It drives 32-ohm headphones without the thin, hissy output most phone dongles settle for, and the aluminium shell does not flex in a bag.",
        "mrp": "429.00",
        "price": "349.00",
        "tax": 0,
        "category": "audio",
        "brand": "lumen-forge",
        "stock": 42,
        "featured": False,
        "bestseller": False,
        "specs": {"output": "3.5mm", "chip": "ES9218P class", "length": "12cm"},
    },
    {
        "name": "Harbor Current Sport Earbuds",
        "sku": "HB-CRNT-23",
        "short": "Secure-fit wireless earbuds for runs that actually stay in.",
        "description": "Harbor Current uses wingtips instead of hoping friction will do the work. IPX7 sealing, a USB-C case, and an EQ that keeps footsteps audible so you are not boxed in on a shared path.",
        "mrp": "649.00",
        "price": "549.00",
        "tax": 0,
        "category": "audio",
        "brand": "harbor",
        "stock": 38,
        "featured": True,
        "bestseller": False,
        "specs": {"driver": "11mm", "battery": "32 hours with case", "rating": "IPX7"},
    },
    {
        "name": "Pebble Shelf Desktop Speaker",
        "sku": "PB-SHELF-24",
        "short": "A USB-powered stereo pair for desks that cannot host a soundbar.",
        "description": "Pebble Shelf is two small cabinets with a 3.5mm plus USB-C input. The voicing is mid-forward for calls and albums, not the hollow bass most RGB desktop speakers chase.",
        "mrp": "799.00",
        "price": "649.00",
        "tax": 0,
        "category": "audio",
        "brand": "pebble-and-co",
        "stock": 26,
        "featured": False,
        "bestseller": True,
        "specs": {"output": "2x 8W", "inputs": "USB-C, 3.5mm", "size": "12cm cabinets"},
    },
    {
        "name": "Northline QuietShell ANC Earbuds",
        "sku": "NL-QSHL-25",
        "short": "Hybrid ANC earbuds for buses, offices, and late trains.",
        "description": "Northline QuietShell uses feed-forward plus in-ear mics so cabin noise drops without turning voices into mush. Transparency mode is a physical button, not a buried app toggle.",
        "mrp": "999.00",
        "price": "849.00",
        "tax": 0,
        "category": "audio",
        "brand": "northline",
        "stock": 30,
        "featured": True,
        "bestseller": True,
        "specs": {"anc": "Hybrid", "battery": "30 hours with case", "connectivity": "Bluetooth 5.4"},
    },
    {
        "name": "Lumen Forge Hall Wireless Headphones",
        "sku": "LF-HALL-26",
        "short": "Over-ear wireless headphones with a wide, unforced soundstage.",
        "description": "Lumen Forge Hall is a travel headphone that folds flat in a sling. Multipoint Bluetooth, a 32-hour battery, and pads that do not cook your ears after an hour of calls.",
        "mrp": "1000.00",
        "price": "949.00",
        "tax": 0,
        "category": "audio",
        "brand": "lumen-forge",
        "stock": 20,
        "featured": True,
        "bestseller": False,
        "specs": {"type": "Closed-back wireless", "battery": "32 hours", "fold": "Flat-fold hinges"},
    },
    {
        "name": "Northline GaN 65W Charger",
        "sku": "NL-GAN65-04",
        "short": "A compact two-port charger for laptop and phone together.",
        "description": "GaN internals keep the brick small enough for a sling bag. One USB-C port can feed a thin laptop; the second keeps a phone topped up.",
        "mrp": "199.00",
        "price": "149.00",
        "tax": 0,
        "category": "charging",
        "brand": "northline",
        "stock": 60,
        "featured": True,
        "bestseller": True,
        "specs": {"output": "65W", "ports": "2x USB-C", "foldable_plug": True},
    },
    {
        "name": "Harbor Braid USB-C Cable 1.8m",
        "sku": "HB-CBL18-05",
        "short": "A braided cable that reaches the sofa without stretching.",
        "description": "Rated for 100W charging and 480Mbps data. The strain relief is oversized because that is where most cables fail.",
        "mrp": "49.00",
        "price": "30.00",
        "tax": 0,
        "category": "charging",
        "brand": "harbor",
        "stock": 120,
        "featured": True,
        "bestseller": True,
        "specs": {"length": "1.8m", "power": "100W", "data": "USB 2.0"},
    },
    {
        "name": "Harbor Pocket 20W USB-C Charger",
        "sku": "HB-W20-35",
        "short": "A single-port 20W brick that does not hog the strip.",
        "description": "Harbor Pocket is for overnight phone charging without a laptop brick. The plug folds, the shell stays cool, and 20W is enough for a typical USB-C phone overnight.",
        "mrp": "149.00",
        "price": "109.00",
        "tax": 0,
        "category": "charging",
        "brand": "harbor",
        "stock": 88,
        "featured": False,
        "bestseller": True,
        "specs": {"output": "20W", "ports": "1x USB-C", "foldable_plug": True},
    },
    {
        "name": "Northline Reach USB-C Cable 3m",
        "sku": "NL-CBL3-36",
        "short": "A 3-metre braided cable for the far side of the sofa.",
        "description": "Northline Reach is rated for 60W charging. The extra length is for floor sockets behind a bed, not for wrapping around a chair leg.",
        "mrp": "179.00",
        "price": "129.00",
        "tax": 0,
        "category": "charging",
        "brand": "northline",
        "stock": 74,
        "featured": False,
        "bestseller": False,
        "specs": {"length": "3m", "power": "60W", "data": "USB 2.0"},
    },
    {
        "name": "Pebble Carry 10000mAh Power Bank",
        "sku": "PB-PB10-37",
        "short": "A pocket power bank that covers a day of maps and calls.",
        "description": "Pebble Carry is 10,000mAh with USB-C in and out. No display gimmicks, no RGB. It is sized for a jacket pocket, not a camera bag.",
        "mrp": "249.00",
        "price": "199.00",
        "tax": 0,
        "category": "charging",
        "brand": "pebble-and-co",
        "stock": 62,
        "featured": True,
        "bestseller": True,
        "specs": {"capacity": "10000mAh", "ports": "USB-C + USB-A", "input": "USB-C 18W"},
    },
    {
        "name": "Lumen Forge 30W GaN Charger",
        "sku": "LF-GAN30-38",
        "short": "A 30W GaN brick for phones and small tablets together.",
        "description": "Lumen Forge 30W uses GaN so the brick stays small. One USB-C port at 30W, one USB-A for a second device that only needs a trickle.",
        "mrp": "349.00",
        "price": "279.00",
        "tax": 0,
        "category": "charging",
        "brand": "lumen-forge",
        "stock": 48,
        "featured": False,
        "bestseller": False,
        "specs": {"output": "30W", "ports": "USB-C + USB-A", "foldable_plug": True},
    },
    {
        "name": "Harbor Drive 45W Car Charger",
        "sku": "HB-CAR45-39",
        "short": "A 45W dual-port charger for the 12V socket.",
        "description": "Harbor Drive feeds a laptop-lite or two phones from the car. The body is short so it does not block the neighbouring socket, and it stays put on bad roads.",
        "mrp": "429.00",
        "price": "349.00",
        "tax": 0,
        "category": "charging",
        "brand": "harbor",
        "stock": 40,
        "featured": False,
        "bestseller": False,
        "specs": {"output": "45W", "ports": "USB-C + USB-A", "input": "12V"},
    },
    {
        "name": "Northline Snap Wireless Pad",
        "sku": "NL-SNAP-40",
        "short": "A 15W wireless pad that does not cook the phone overnight.",
        "description": "Northline Snap uses a foreign-object check and a cooler coil than most pad chargers. It is for a bedside table, not a racing charge before a flight.",
        "mrp": "549.00",
        "price": "449.00",
        "tax": 0,
        "category": "charging",
        "brand": "northline",
        "stock": 36,
        "featured": True,
        "bestseller": False,
        "specs": {"output": "15W wireless", "input": "USB-C", "coil": "Single"},
    },
    {
        "name": "Pebble Trek 20000mAh Power Bank",
        "sku": "PB-PB20-41",
        "short": "A 20,000mAh pack for weekends when sockets are scarce.",
        "description": "Pebble Trek has USB-C PD out for a small laptop sip and a second USB-A for a phone. The shell is rubberised because this is the pack that lives in a backpack.",
        "mrp": "649.00",
        "price": "549.00",
        "tax": 0,
        "category": "charging",
        "brand": "pebble-and-co",
        "stock": 28,
        "featured": True,
        "bestseller": True,
        "specs": {"capacity": "20000mAh", "output": "USB-C PD 30W", "ports": "USB-C + USB-A"},
    },
    {
        "name": "Lumen Forge 100W GaN Cube",
        "sku": "LF-GAN100-42",
        "short": "A 100W three-port GaN charger for laptop, tablet, and phone.",
        "description": "Lumen Forge Cube replaces a laptop brick on short trips. Two USB-C ports share 100W; a USB-A port covers older accessories. The plug folds for a sling bag.",
        "mrp": "949.00",
        "price": "799.00",
        "tax": 0,
        "category": "charging",
        "brand": "lumen-forge",
        "stock": 22,
        "featured": True,
        "bestseller": False,
        "specs": {"output": "100W", "ports": "2x USB-C + USB-A", "foldable_plug": True},
    },
    {
        "name": "Lumen Forge 1TB NVMe Drive",
        "sku": "LF-NV1T-06",
        "short": "Internal storage for photo libraries and project files.",
        "description": "A DRAM-less NVMe drive tuned for consistent everyday writes rather than burst-benchmark theatre.",
        "mrp": "849.00",
        "price": "699.00",
        "tax": 0,
        "category": "storage",
        "brand": "lumen-forge",
        "stock": 28,
        "featured": True,
        "bestseller": False,
        "specs": {"capacity": "1TB", "interface": "PCIe Gen4", "form": "M.2 2280"},
    },
    {
        "name": "Pebble Pocket 512GB SSD",
        "sku": "PB-SSD512-07",
        "short": "Pocket SSD with a rubberised shell for bag travel.",
        "description": "USB-C portable SSD for editors who bounce between home and studio. No RGB, no sharp corners.",
        "mrp": "799.00",
        "price": "649.00",
        "tax": 0,
        "category": "storage",
        "brand": "pebble-and-co",
        "stock": 40,
        "featured": False,
        "bestseller": False,
        "specs": {"capacity": "512GB", "interface": "USB 3.2", "weight": "48g"},
    },
    {
        "name": "Harbor Flash 32GB USB Drive",
        "sku": "HB-USB32-28",
        "short": "A small USB stick for presentations and exam forms.",
        "description": "Harbor Flash is a metal-cap 32GB drive that does not snag in a pocket. The connector is USB-A, because that is still what most college labs and print shops have.",
        "mrp": "149.00",
        "price": "109.00",
        "tax": 0,
        "category": "storage",
        "brand": "harbor",
        "stock": 110,
        "featured": False,
        "bestseller": True,
        "specs": {"capacity": "32GB", "interface": "USB 2.0", "body": "Metal cap"},
    },
    {
        "name": "Northline 64GB microSD Card",
        "sku": "NL-SD64-27",
        "short": "A U1 microSD card for phones, cameras, and dash cams.",
        "description": "Northline 64GB is rated for Full HD video without dropping frames on a mid-range phone. The adapter is in the sleeve so a laptop SD slot still works.",
        "mrp": "179.00",
        "price": "129.00",
        "tax": 0,
        "category": "storage",
        "brand": "northline",
        "stock": 95,
        "featured": False,
        "bestseller": True,
        "specs": {"capacity": "64GB", "speed": "UHS-I U1", "adapter": "SD included"},
    },
    {
        "name": "Pebble Clip 128GB USB-C Stick",
        "sku": "PB-CLIP-29",
        "short": "A dual-ended stick for phones and laptops that only have USB-C.",
        "description": "Pebble Clip has USB-C on one end and USB-A on the other. 128GB is enough for a semester of notes and a weekend of photos without another cloud login.",
        "mrp": "249.00",
        "price": "199.00",
        "tax": 0,
        "category": "storage",
        "brand": "pebble-and-co",
        "stock": 70,
        "featured": True,
        "bestseller": False,
        "specs": {"capacity": "128GB", "ports": "USB-C + USB-A", "speed": "USB 3.2"},
    },
    {
        "name": "Harbor Vault 256GB microSD",
        "sku": "HB-SD256-30",
        "short": "A 256GB card for 4K cameras and long commute recordings.",
        "description": "Harbor Vault is V30-rated so 4K capture does not stutter. A write-protect slider on the adapter is included because accidental format is how most cards die.",
        "mrp": "349.00",
        "price": "279.00",
        "tax": 0,
        "category": "storage",
        "brand": "harbor",
        "stock": 58,
        "featured": False,
        "bestseller": False,
        "specs": {"capacity": "256GB", "speed": "UHS-I V30", "adapter": "SD included"},
    },
    {
        "name": "Pebble Shield 2.5-inch Enclosure",
        "sku": "PB-CASE-31",
        "short": "A USB-C enclosure that turns a spare laptop drive into a pocket disk.",
        "description": "Pebble Shield holds a 2.5-inch SATA SSD or HDD. The shell is rubberised, the cable is USB-C, and there is no RGB because a backup disk should look boring.",
        "mrp": "429.00",
        "price": "349.00",
        "tax": 0,
        "category": "storage",
        "brand": "pebble-and-co",
        "stock": 44,
        "featured": False,
        "bestseller": False,
        "specs": {"bay": "2.5-inch SATA", "interface": "USB-C 3.1", "tool": "No-screw tray"},
    },
    {
        "name": "Lumen Forge 256GB NVMe Drive",
        "sku": "LF-NV256-32",
        "short": "A 256GB NVMe upgrade for thin laptops that shipped with eMMC.",
        "description": "Lumen Forge 256GB is sized for a working OS plus documents, not a game library. DRAM-less, Gen3, and short enough for most ultrabook shields.",
        "mrp": "529.00",
        "price": "429.00",
        "tax": 0,
        "category": "storage",
        "brand": "lumen-forge",
        "stock": 36,
        "featured": True,
        "bestseller": False,
        "specs": {"capacity": "256GB", "interface": "PCIe Gen3", "form": "M.2 2280"},
    },
    {
        "name": "Northline Desk 1TB Hard Drive",
        "sku": "NL-HDD1T-33",
        "short": "A quiet 1TB 2.5-inch drive for photo dumps and weekly backups.",
        "description": "Northline Desk is a 5400-rpm laptop drive. Pair it with an enclosure for a cheap archive; leave it internal if you are replacing a dying 500GB disk.",
        "mrp": "649.00",
        "price": "549.00",
        "tax": 0,
        "category": "storage",
        "brand": "northline",
        "stock": 32,
        "featured": False,
        "bestseller": True,
        "specs": {"capacity": "1TB", "form": "2.5-inch SATA", "speed": "5400 rpm"},
    },
    {
        "name": "Lumen Forge Archive 2TB Hard Drive",
        "sku": "LF-HDD2T-34",
        "short": "A 2TB disk for family photos and project files that should not live only on a laptop.",
        "description": "Lumen Forge Archive is a 2.5-inch 2TB drive. It is slower than NVMe on purpose: this is the copy you keep, not the copy you edit.",
        "mrp": "949.00",
        "price": "799.00",
        "tax": 0,
        "category": "storage",
        "brand": "lumen-forge",
        "stock": 24,
        "featured": True,
        "bestseller": False,
        "specs": {"capacity": "2TB", "form": "2.5-inch SATA", "speed": "5400 rpm"},
    },
    {
        "name": "Harbor Tide Smartwatch",
        "sku": "HB-TIDE-08",
        "short": "A quiet smartwatch with readable outdoor display.",
        "description": "Harbor Tide tracks sleep and walks without turning your wrist into a notification billboard. Default watch face is analogue.",
        "mrp": "999.00",
        "price": "899.00",
        "tax": 0,
        "category": "wearables",
        "brand": "harbor",
        "stock": 33,
        "featured": True,
        "bestseller": True,
        "specs": {"display": "1.43 AMOLED", "battery": "7 days typical", "water": "5ATM"},
    },
    {
        "name": "Northline Knit Watch Band",
        "sku": "NL-BAND-09",
        "short": "Breathable knit band for 20mm and 22mm lugs.",
        "description": "A sport-mesh band that dries quickly after a commute. Hardware is brushed steel, not chrome plastic.",
        "mrp": "99.00",
        "price": "79.00",
        "tax": 0,
        "category": "wearables",
        "brand": "northline",
        "stock": 75,
        "featured": False,
        "bestseller": False,
        "specs": {"widths": "20mm / 22mm", "material": "Recycled knit"},
    },
    {
        "name": "Northline Paper 14 Laptop",
        "sku": "NL-PPR14-10",
        "short": "A 14-inch laptop aimed at writing, calls, and light design.",
        "description": "Northline Paper 14 favours battery life and a low-glare screen. The keyboard has 1.5mm travel because mushy chiclet keys waste afternoons.",
        "mrp": "1000.00",
        "price": "999.00",
        "tax": 0,
        "category": "computing",
        "brand": "northline",
        "stock": 12,
        "featured": True,
        "bestseller": False,
        "specs": {"display": "14-inch 2.2K", "ram": "16GB", "storage": "512GB", "weight": "1.28kg"},
    },
    {
        "name": "Lumen Forge USB-C Hub 7-in-1",
        "sku": "LF-HUB7-11",
        "short": "A desk hub with HDMI, ethernet, and SD without dongle chaos.",
        "description": "Aluminium body, passthrough charging, and ports spaced so fat USB drives do not block neighbours.",
        "mrp": "449.00",
        "price": "349.00",
        "tax": 0,
        "category": "computing",
        "brand": "lumen-forge",
        "stock": 44,
        "featured": False,
        "bestseller": True,
        "specs": {"ports": "HDMI 4K, USB-A x2, USB-C, SD, microSD, Ethernet"},
    },
    {
        "name": "Pebble Arc Controller",
        "sku": "PB-ARC-12",
        "short": "Wireless controller with Hall-effect sticks.",
        "description": "Built for long sessions on PC and TV boxes. Triggers are linear, not clicky, and the d-pad is actual four-way.",
        "mrp": "749.00",
        "price": "599.00",
        "tax": 0,
        "category": "gaming",
        "brand": "pebble-and-co",
        "stock": 26,
        "featured": True,
        "bestseller": True,
        "specs": {"sticks": "Hall effect", "battery": "18 hours", "connectivity": "2.4GHz + Bluetooth"},
    },
    {
        "name": "Harbor QuietPlay Headset",
        "sku": "HB-QP-13",
        "short": "Lightweight gaming headset that does not clamp your temples.",
        "description": "Open-leaning sound for footsteps without turning the mix into a nightclub. Mic is detachable for travel.",
        "mrp": "699.00",
        "price": "549.00",
        "tax": 0,
        "category": "gaming",
        "brand": "harbor",
        "stock": 31,
        "featured": False,
        "bestseller": False,
        "specs": {"weight": "268g", "mic": "Detachable boom", "connection": "USB-C / 3.5mm"},
    },
    {
        "name": "Kettlehouse AirLeaf Tower Fan",
        "sku": "KH-FAN-14",
        "short": "A slim tower fan with a quiet night curve.",
        "description": "Designed for apartments where a pedestal fan eats walking space. Oscillation is wide; the remote is not infrared-only theatre.",
        "mrp": "949.00",
        "price": "799.00",
        "tax": 1,
        "category": "home-appliances",
        "brand": "kettlehouse",
        "stock": 18,
        "featured": True,
        "bestseller": False,
        "specs": {"height": "96cm", "modes": "4", "timer": "8 hours"},
    },
    {
        "name": "Kettlehouse SteamFold Iron",
        "sku": "KH-IRON-15",
        "short": "A compact steam iron with a ceramic plate.",
        "description": "Light enough for a weekly shirt pile. Anti-drip at low temperatures, which is the setting most people actually use.",
        "mrp": "249.00",
        "price": "199.00",
        "tax": 1,
        "category": "home-appliances",
        "brand": "kettlehouse",
        "stock": 40,
        "featured": False,
        "bestseller": True,
        "specs": {"wattage": "1600W", "soleplate": "Ceramic", "tank": "220ml"},
    },
    {
        "name": "Kettlehouse Brew Mini Kettle",
        "sku": "KH-KTL-16",
        "short": "0.8 litre kettle for studios and small kitchens.",
        "description": "Boils enough water for two mugs without the bulk of a 1.8 litre jug. Auto shut-off and a cool-touch handle.",
        "mrp": "329.00",
        "price": "249.00",
        "tax": 1,
        "category": "kitchen",
        "brand": "kettlehouse",
        "stock": 52,
        "featured": False,
        "bestseller": True,
        "specs": {"capacity": "0.8L", "wattage": "1200W", "material": "Stainless steel"},
    },
    {
        "name": "Pebble Morning Mixer",
        "sku": "PB-MIX-17",
        "short": "A 500W mixer that does not monopolise the counter.",
        "description": "Three jars, a pulse toggle, and a base that stays put. Overload protection is standard, not a brochure extra.",
        "mrp": "649.00",
        "price": "499.00",
        "tax": 1,
        "category": "kitchen",
        "brand": "pebble-and-co",
        "stock": 24,
        "featured": True,
        "bestseller": False,
        "specs": {"power": "500W", "jars": 3, "body": "ABS"},
    },
    {
        "name": "Lumen Forge Desk Lamp",
        "sku": "LF-LAMP-18",
        "short": "Adjustable LED lamp with a warm-to-neutral range.",
        "description": "Built for evening reading and video calls. The arm holds position; the base is weighted so it does not tip when you swing it.",
        "mrp": "399.00",
        "price": "299.00",
        "tax": 0,
        "category": "home-appliances",
        "brand": "lumen-forge",
        "stock": 37,
        "featured": False,
        "bestseller": False,
        "specs": {"cri": "90+", "cct": "3000-5000K", "power": "10W"},
    },
]


CATEGORY_TAGS = {
    "audio": ["audio", "sound"],
    "charging": ["charging", "power", "cables"],
    "storage": ["storage", "files"],
    "wearables": ["wearables", "watch"],
    "computing": ["computing", "laptop"],
    "gaming": ["gaming", "play"],
    "home-appliances": ["home", "appliances"],
    "kitchen": ["kitchen", "compact"],
}

PRODUCT_TAGS = {
    "HB-PLSE-01": ["earbuds", "wireless", "commute"],
    "LF-STUD-02": ["headphones", "studio"],
    "PB-SHFT-03": ["speaker", "bluetooth"],
    "NL-LOOP-19": ["earbuds", "wired", "3.5mm"],
    "PB-REED-20": ["iem", "wired", "monitors"],
    "HB-DRFT-21": ["neckband", "wireless", "sport"],
    "LF-DAC-22": ["dac", "usb-c", "dongle"],
    "HB-CRNT-23": ["earbuds", "wireless", "sport"],
    "PB-SHELF-24": ["speaker", "desktop", "usb"],
    "NL-QSHL-25": ["earbuds", "anc", "wireless"],
    "LF-HALL-26": ["headphones", "wireless", "over-ear"],
    "NL-GAN65-04": ["charger", "gan", "usb-c"],
    "HB-CBL18-05": ["cable", "usb-c", "braided"],
    "HB-W20-35": ["charger", "20w", "usb-c"],
    "NL-CBL3-36": ["cable", "usb-c", "3m"],
    "PB-PB10-37": ["powerbank", "10000mah"],
    "LF-GAN30-38": ["charger", "gan", "30w"],
    "HB-CAR45-39": ["car", "charger", "45w"],
    "NL-SNAP-40": ["wireless", "pad", "15w"],
    "PB-PB20-41": ["powerbank", "20000mah"],
    "LF-GAN100-42": ["charger", "gan", "100w"],
    "LF-NV1T-06": ["ssd", "nvme"],
    "PB-SSD512-07": ["ssd", "portable"],
    "HB-USB32-28": ["usb", "flash", "32gb"],
    "NL-SD64-27": ["microsd", "sd", "64gb"],
    "PB-CLIP-29": ["usb-c", "flash", "128gb"],
    "HB-SD256-30": ["microsd", "sd", "256gb"],
    "PB-CASE-31": ["enclosure", "sata", "2.5"],
    "LF-NV256-32": ["ssd", "nvme", "256gb"],
    "NL-HDD1T-33": ["hdd", "1tb", "sata"],
    "LF-HDD2T-34": ["hdd", "2tb", "archive"],
    "HB-TIDE-08": ["smartwatch"],
    "NL-BAND-09": ["band", "strap"],
    "NL-PPR14-10": ["laptop", "notebook"],
    "LF-HUB7-11": ["hub", "usb-c"],
    "PB-ARC-12": ["controller"],
    "HB-QP-13": ["headset", "gaming"],
    "KH-FAN-14": ["fan", "cooling"],
    "KH-IRON-15": ["iron", "steam"],
    "KH-KTL-16": ["kettle"],
    "PB-MIX-17": ["mixer"],
    "LF-LAMP-18": ["lamp", "desk"],
}


def _product_tags(item):
    tags = list(CATEGORY_TAGS.get(item["category"], [item["category"]]))
    tags.append(item["brand"].replace("-", " "))
    tags.extend(PRODUCT_TAGS.get(item["sku"], []))
    if item.get("featured"):
        tags.append("featured")
    if item.get("bestseller"):
        tags.append("bestseller")
    return tags


class Command(BaseCommand):
    help = "Seed original catalog, tax classes, settings, admin user, and a demo coupon."

    def handle(self, *args, **options):
        tax_objects = []
        for name, hsn, cgst, sgst, igst in TAX:
            obj, _ = TaxClass.objects.update_or_create(
                name=name,
                defaults={"hsn_sac_code": hsn, "cgst_rate": cgst, "sgst_rate": sgst, "igst_rate": igst, "is_active": True},
            )
            tax_objects.append(obj)

        categories = {}
        for index, (name, slug, description) in enumerate(CATEGORIES):
            categories[slug], _ = Category.objects.update_or_create(
                slug=slug,
                defaults={"name": name, "description": description, "is_active": True, "sort_order": index},
            )

        brands = {}
        for name, slug in BRANDS:
            brands[slug], _ = Brand.objects.update_or_create(slug=slug, defaults={"name": name, "is_active": True})

        for item in PRODUCTS:
            product, _ = Product.objects.update_or_create(
                sku=item["sku"],
                defaults={
                    "name": item["name"],
                    "slug": item["sku"].lower(),
                    "description": item["description"],
                    "short_description": item["short"],
                    "mrp": item["mrp"],
                    "selling_price": item["price"],
                    "tax_class": tax_objects[item["tax"]],
                    "category": categories[item["category"]],
                    "brand": brands[item["brand"]],
                    "specifications": item["specs"],
                    "tags": _product_tags(item),
                    "stock_quantity": item["stock"],
                    "is_active": True,
                    "is_featured": item["featured"],
                    "is_bestseller": item["bestseller"],
                },
            )
            Inventory.objects.update_or_create(
                product=product,
                defaults={"quantity": item["stock"], "reserved_quantity": 0, "low_stock_threshold": 5},
            )
            image_path = IMAGE_DIR / f"{item['sku']}.png"
            if image_path.exists() and not product.images.exists():
                with image_path.open("rb") as handle:
                    photo = ProductImage(product=product, alt_text=item["name"], is_primary=True, sort_order=0)
                    photo.image.save(f"{item['sku']}.png", File(handle), save=True)

        now = timezone.now()
        Coupon.objects.update_or_create(
            code="NEXORA10",
            defaults={
                "description": "10% off orders above ₹199",
                "discount_type": Coupon.DiscountType.PERCENT,
                "value": "10.00",
                "min_order_amount": "199.00",
                "max_discount_amount": "1500.00",
                "usage_limit": 500,
                "usage_limit_per_user": 3,
                "starts_at": now - timedelta(days=1),
                "ends_at": now + timedelta(days=180),
                "is_active": True,
            },
        )

        defaults = {
            "store_name": "Nexora",
            "origin_state": "Chhattisgarh",
            "shipping_flat_rate": "0.00",
            "free_shipping_threshold": "0.00",
            "support_email": "hello@nexora.local",
            "currency": "INR",
        }
        for key, value in defaults.items():
            StoreSetting.objects.update_or_create(key=key, defaults={"value": value})

        if not User.objects.filter(email="admin@nexora.local").exists():
            User.objects.create_superuser(
                username="admin@nexora.local",
                email="admin@nexora.local",
                password="AdminPass123!",
                role=User.Role.SUPER_ADMIN,
                first_name="Nexora",
                last_name="Admin",
            )
        self.stdout.write(self.style.SUCCESS("Catalog, settings, coupon, and admin user are ready."))
