# Generated by Django 5.2.17 on 2026-08-26 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_review_status(apps, schema_editor):
    Review = apps.get_model("engagement", "Review")
    Review.objects.filter(is_approved=True).update(status="APPROVED")
    Review.objects.filter(is_approved=False).update(status="PENDING")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_search_document_product_tags_and_more'),
        ('engagement', '0002_add_timestamps'),
        ('orders', '0004_alter_orderitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.RunPython(backfill_review_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'status'], name='engagement__product_990d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'status'], name='engagement__user_id_cb5b34_idx'),
        ),
    ]
