# Generated by Django 5.2.17 on 2026-08-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=8),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='mock', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verification_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('event_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate')], default='PROCESSED', max_length=16)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=240)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='orders.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['event_id'], name='orders_paym_event_i_5a1199_idx'), models.Index(fields=['provider', 'event_type'], name='orders_paym_provide_9b48b1_idx')],
            },
        ),
    ]
