# Generated by Django 5.2.17 on 2026-08-26 14:09

from django.db import migrations, models


def _compose_search_document(name, sku, brand_name, category_name, short_description, description, tags):
    tag_list = tags if isinstance(tags, list) else []
    parts = [name or "", sku or "", brand_name or "", category_name or "", short_description or "", description or "", *tag_list]
    return " ".join(str(part) for part in parts if part).lower()


def fill_search_documents(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.select_related("brand", "category").iterator():
        brand_name = getattr(product.brand, "name", "") if product.brand_id else ""
        category_name = getattr(product.category, "name", "") if product.category_id else ""
        document = _compose_search_document(
            product.name,
            product.sku,
            brand_name,
            category_name,
            product.short_description,
            product.description,
            product.tags,
        )
        if product.search_document != document:
            Product.objects.filter(pk=product.pk).update(search_document=document)


def create_postgres_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS catalog_product_search_tsv "
        "ON catalog_product USING gin (to_tsvector('english', coalesce(search_document, '')));"
    )
    schema_editor.execute("CREATE INDEX IF NOT EXISTS catalog_product_tags_gin ON catalog_product USING gin (tags);")
    try:
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS catalog_product_name_trgm ON catalog_product USING gin (name gin_trgm_ops);"
        )
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS catalog_product_sku_trgm ON catalog_product USING gin (sku gin_trgm_ops);"
        )
    except Exception:
        pass


def drop_postgres_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP INDEX IF EXISTS catalog_product_search_tsv;")
    schema_editor.execute("DROP INDEX IF EXISTS catalog_product_tags_gin;")
    schema_editor.execute("DROP INDEX IF EXISTS catalog_product_name_trgm;")
    schema_editor.execute("DROP INDEX IF EXISTS catalog_product_sku_trgm;")


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_brand_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="search_document",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active", "selling_price"], name="catalog_prod_active_price"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active", "stock_quantity"], name="catalog_prod_active_stock"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active", "created_at"], name="catalog_prod_active_created"),
        ),
        migrations.RunPython(fill_search_documents, migrations.RunPython.noop),
        migrations.RunPython(create_postgres_search_indexes, drop_postgres_search_indexes),
    ]
